function dLengthR = dSpringLengthR(in1,in2)
%DSPRINGLENGTHR
%    DLENGTHR = DSPRINGLENGTHR(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    12-Feb-2017 19:57:29

alphaR = in1(4,:);
betaR = in1(5,:);
lH = in2(:,3);
lL2 = in2(:,7);
lL3 = in2(:,11);
phi = in1(3,:);
valphaR = in1(11,:);
vbetaR = in1(12,:);
t2 = alphaR+betaR+phi;
t3 = sin(t2);
t4 = alphaR+phi;
t5 = cos(t2);
t6 = cos(t4);
t7 = lL2.*t6;
t8 = cos(phi);
t9 = lH.*t8;
t10 = lL3.*t5;
t11 = t7+t9+t10;
t12 = sin(t4);
t13 = lL2.*t12;
t14 = sin(phi);
t15 = lH.*t14;
t16 = lL3.*t3;
t17 = t13+t15+t16;
t18 = t11.^2;
t19 = t17.^2;
t20 = t18+t19;
t21 = 1.0./sqrt(t20);
dLengthR = t21.*vbetaR.*(lL3.*t3.*t11.*2.0-lL3.*t5.*t17.*2.0).*(-1.0./2.0)+t21.*valphaR.*(t17.*(t7+t10).*2.0-t11.*(t13+t16).*2.0).*(1.0./2.0);
