function LengthL = SpringLengthL(in1,in2)
%SPRINGLENGTHL
%    LENGTHL = SPRINGLENGTHL(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    12-Feb-2017 19:57:34

alphaL = in1(6,:);
betaL = in1(7,:);
lH = in2(:,3);
lL2 = in2(:,7);
lL3 = in2(:,11);
phi = in1(3,:);
t3 = alphaL+phi;
t4 = alphaL+betaL+phi;
t2 = lH.*cos(phi)+lL2.*cos(t3)+lL3.*cos(t4);
t5 = lH.*sin(phi)+lL2.*sin(t3)+lL3.*sin(t4);
LengthL = sqrt(t2.^2+t5.^2);
