function dthetaR_HK = dThetaR_HK(in1,in2)
%DTHETAR_HK
%    DTHETAR_HK = DTHETAR_HK(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    12-Feb-2017 19:57:35

alphaR = in1(4,:);
lL2 = in2(:,7);
phi = in1(3,:);
valphaR = in1(11,:);
vphi = in1(10,:);
t2 = alphaR+phi;
t4 = cos(t2);
t5 = lL2.*t4;
t6 = sin(t2);
t7 = lL2.*t6;
t12 = imag(t5);
t13 = real(t7);
t3 = t12+t13;
t9 = real(t5);
t10 = imag(t7);
t8 = -t9+t10;
t11 = t9-t10;
t14 = t3.^2;
t15 = t11.^2;
t16 = 1.0./t11.^2;
t17 = t14.*t16;
t18 = t17+1.0;
dthetaR_HK = (t15.*t18.*vphi)./(t14+t15)+(t15.*t18.*valphaR)./(t14+t8.^2);
