function LengthR = SpringLengthR(in1,in2)
%SPRINGLENGTHR
%    LENGTHR = SPRINGLENGTHR(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    12-Feb-2017 17:50:35

alphaR = in1(4,:);
betaR = in1(5,:);
lH = in2(:,3);
lL2 = in2(:,7);
lL3 = in2(:,11);
phi = in1(3,:);
t3 = alphaR+phi;
t4 = alphaR+betaR+phi;
t2 = lH.*cos(phi)+lL2.*cos(t3)+lL3.*cos(t4);
t5 = lH.*sin(phi)+lL2.*sin(t3)+lL3.*sin(t4);
LengthR = sqrt(t2.^2+t5.^2);
